# basic options
title: StuartsProjects
author: GitHub User
#email: your-email@domain.com
description: Adventures with Semtech LoRa devices
#twitter_username: jekyllrb
github_username:  StuartsProjects

#build settings
markdown: kramdown
theme: minima
