# basic options
title: StuartsProjects
author: Stuart
#email: your-email@domain.com
description: Adventures with Semtech LoRa® devices. LoRa® is a Semtech registered trademark. 
#twitter_username: jekyllrb
github_username:  StuartsProjects

#build settings
markdown: kramdown
#theme: jekyll-theme-cayman
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag